link:
  datasource:
    host: 192.168.150.101
    port: 3306
    database: link_db
    username: root
    password: linkpulse123
  redis:
    host: 192.168.150.101
    port: 6379
    password: linkpulse123
    database: 0
    timeout: 2000
# todo 由于服务器资源有限，项目暂时不使用 RabbitMQ，相关配置注释掉，后续可根据需要启用并调整连接信息
#  rabbitmq:
#    host: 192.168.150.101
#    port: 5672
#    username: root
#    password: linkpulse123
#    virtual-host: /linkPulse
  redirect:
    url-prefix: "http://localhost:8080/"
  logging:
    level:
      com.hejiale: debug
      org.springframework.ai.chat.client.advisor: debug
  cors:
    allowed-origins: "*"