link:
  datasource:
    host: 192.168.150.101
    port: 3306
    database: link_pulse
    username: root
    password: 123
  redis:
    host: 192.168.150.101
    port: 6379
    password: 123321
    database: 0
    timeout: 2000
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: linkpulse
    password: 123
    virtual-host: /linkPulse
  redirect:
    url-prefix: "http://localhost:8080/"