server:
  port: 8080 #端口
  tomcat:
    uri-encoding: UTF-8 #服务编码

spring:
  profiles:
    active: local # 激活本地环境配置
  datasource:
    url: jdbc:mysql://192.168.150.101:3306/link_pulse?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   # 指定返回json日期格式
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.150.101      # 服务地址
    port: 5672           # 端口，默认5672
    username: linkpulse      # 用户名
    password: 123      # 密码
    virtual-host: /linkPulse      # 虚拟主机
  data:
    redis:
      host: 192.168.150.101
      port: 6379
      password: 123321
      database: 0
      timeout: 3000ms

logging:
  level:
    com.hejiale: debug

link:
  jwt:
    # 设置 jwt 签名加密时使用的秘钥
    secret-key: linkPulse-secretKey-2026-secure-key!
    # 设置 jwt 过期时间
    ttl: 3600000000000
    # 设置前端传递过来的令牌名称
    token-name: token
  url:
    prefix:${link.url.prefix} # 设置前端访问的 url 前缀